stages:
  - test


######################## Variables #########################
variables:
  ACTION_IMAGE: jppgomes/jp:latest
  TELEGRAM_IMAGE: jppgomes/jp-telegram:latest
  INTERCAMPI_IMAGE: $jppgomes/jp-intercampi:latest


######################## Tests #############################
test_flake8:
  image: ejplatform/python:alpine
  stage: test
  script:
    pip install --upgrade pip && pip install -r requirements.txt && pip install progressbar33 && pip install pytest && pip install --upgrade setuptools && pip install ez_setup && pip install unroll && ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install --upgrade numpy pandas && pip install pymongo && source .env && cd TestActions && pytest




