version: '3.0'

services:
  action_server:
      image: jp:latest
      environment:      
        ACTION_WEBHOOK: ${ACTION_WEBHOOK} 
        SENDPDF_WEBHOOK: ${SENDPDF_WEBHOOK}
        INTERCAMPI_WEBHOOK: ${INTERCAMPI_WEBHOOK}
        MONGO_ID: ${MONGO_ID}    
      ports:
        - 5055:5055
      volumes:
      - .:/2019.1-Tino    
      command: sh -c "python -m rasa_nlu.train -c nlu/nlu_config.yml --data nlu/nlu_data.md -o models --fixed_model_name nlu --project current --verbose && python -m rasa_core.train -d core/domain.yml -s core/stories.md -o models/current/dialogue && python -m rasa_core_sdk.endpoint --actions actions"
  telegram:
    image: telegram-jp:latest
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_WEBHOOK: ${TELEGRAM_WEBHOOK}
      ACTION_WEBHOOK: ${ACTION_WEBHOOK}
    ports:
      - 5000:5000
    volumes:
      - .:/2019.1-Tino
    command: sh -c "pip install pyfiglet && python -m rasa_nlu.train -c nlu/nlu_config.yml --data nlu/nlu_data.md -o models --fixed_model_name nlu --project current --verbose && python -m rasa_core.train -d core/domain.yml -s core/stories.md -o models/current/dialogue && python main.py"
  intercampi:
    image: intercampi-jp:latest
    environment:      
      INTERCAMPI_WEBHOOK: ${INTERCAMPI_WEBHOOK}
      SENDPDF_WEBHOOK: ${SENDPDF_WEBHOOK}
      ACTION_WEBHOOK: ${ACTION_WEBHOOK}
      MONGO_USER: ${MONGO_USER}
      MONGO_USER: ${MONGO_PASSWORD}
    ports:
      - 5002:5002
    volumes:
      - .:/2019.1-Tino
    command: sh -c "pip install pandas && export FLASK_APP=./microservices/intercampi.py && export FLASK_DEBUG=1 && flask run --host 0.0.0.0 --port 5002"
  send-pdf:
    image: jp-send-pdf:latest
    environment:      
      SENDPDF_WEBHOOK: ${SENDPDF_WEBHOOK}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      ACTION_WEBHOOK: ${ACTION_WEBHOOK}
    ports:
      - 5003:5003
    volumes:
      - .:/2019.1-Tino
    command: sh -c "pip install telegram && pip install python-telegram-bot && export FLASK_APP=./microservices/send-pdf.py && export FLASK_DEBUG=1 && flask run --host 0.0.0.0 --port 5003"

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD} 
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
  redis:
    image: redis:latest


