version: '3.0'

services:
  action_server:
    image: jp:latest
    ports:
      - 5055:5055
    volumes:
    - .:/2019.1-Tino
    command: sh -c "python -m rasa_nlu.train -c nlu/nlu_config.yml --data nlu/nlu_data.md -o models --fixed_model_name nlu --project current --verbose && python -m rasa_core.train -d core/domain.yml -s core/stories.md -o models/current/dialogue && python -m rasa_core_sdk.endpoint --actions actions"
  telegram:
    image: telegram-jp:latest
    ports:
      - 5000:5000
    volumes:
      - .:/2019.1-Tino
    command: sh -c "python -m rasa_nlu.train -c nlu/nlu_config.yml --data nlu/nlu_data.md -o models --fixed_model_name nlu --project current --verbose && python -m rasa_core.train -d core/domain.yml -s core/stories.md -o models/current/dialogue && python main.py"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasa
      MONGO_INITDB_ROOT_PASSWORD: rasa
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
      ME_CONFIG_MONGODB_ADMINPASSWORD: rasa
  redis:
    image: redis:latest

