#Define basicamente como o modelo será treinado e como os recursos serão extraídos.
#Usaremos o pipeline spacy_sklearn predefinido,
#pois temos muito poucos exemplos de treinamento. 

language: "pt"

pipeline:
    - name: "tokenizer_whitespace"
    - name: "ner_crf"
    - name: "ner_synonyms"
    - name: "intent_featurizer_count_vectors"
    - name: "intent_classifier_tensorflow_embedding"