version: '3.0'

services:
  rasa_core:
    image: rasa/rasa_core:latest
    ports:
      - 5005:5005
    volumes:
      - ./models/rasa_core:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - telegram
      - --endpoints
      - ./config/endpoints.yml
      - --credentials
      - ./config/credentials.yml
      - -u
      - current/
  rasa_nlu:
    image: rasa/rasa_nlu:latest-spacy
    volumes:
      - ./models/rasa_nlu:/app/models
    command:
      - start
      - --path
      - models
  # action_server:
  #   image: jp:latest 
  #   volumes:
  #     - ./actions:/app/actions
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASS}
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMIN_PASS}

  redis:
    image: redis:latest
